
import java.awt.image.BufferedImage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Marc
 */
import javax.swing.*;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import java.sql.*;

public class View_Entries extends javax.swing.JFrame {

    public int page = 1;
    public int max;
    public String order = "order by name";
    public boolean error = false;
    String DbURL = "jdbc:mysql://127.0.0.1:3306/your_games";
    String Username = "user";
    String password = "4251";

    /**
     * Creates new form View_Entries
     */
    public View_Entries() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(DbURL, Username, password);
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery("Select COUNT(*) from your_games_records;");
            if (rs.next()) {
                max = rs.getInt(1);
            } else {
                // no record found
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        initComponents();
        updateText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        closeButton1 = new javax.swing.JButton();
        closeButton2 = new javax.swing.JButton();
        closeButton3 = new javax.swing.JButton();
        closeButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Horas1 = new javax.swing.JLabel();
        Consola1 = new javax.swing.JLabel();
        Rating1 = new javax.swing.JLabel();
        Rating2 = new javax.swing.JLabel();
        Consola2 = new javax.swing.JLabel();
        Horas2 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Rating3 = new javax.swing.JLabel();
        Consola3 = new javax.swing.JLabel();
        Horas3 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();
        Rating4 = new javax.swing.JLabel();
        Consola4 = new javax.swing.JLabel();
        Horas4 = new javax.swing.JLabel();
        Nombre4 = new javax.swing.JLabel();
        Rating5 = new javax.swing.JLabel();
        Consola5 = new javax.swing.JLabel();
        Horas5 = new javax.swing.JLabel();
        Nombre5 = new javax.swing.JLabel();
        Portada1 = new javax.swing.JButton();
        Portada2 = new javax.swing.JButton();
        Portada3 = new javax.swing.JButton();
        Portada4 = new javax.swing.JButton();
        Portada5 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(109, 8, 214));

        backButton.setBackground(new java.awt.Color(0, 0, 204));
        backButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(0, 0, 204));
        nextButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(0, 0, 204));
        closeButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        closeButton1.setBackground(new java.awt.Color(0, 0, 204));
        closeButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeButton1.setForeground(new java.awt.Color(255, 255, 255));
        closeButton1.setText("Rating");
        closeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton1ActionPerformed(evt);
            }
        });

        closeButton2.setBackground(new java.awt.Color(0, 0, 204));
        closeButton2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeButton2.setForeground(new java.awt.Color(255, 255, 255));
        closeButton2.setText("Horas");
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });

        closeButton3.setBackground(new java.awt.Color(0, 0, 204));
        closeButton3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeButton3.setForeground(new java.awt.Color(255, 255, 255));
        closeButton3.setText("Nombre");
        closeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton3ActionPerformed(evt);
            }
        });

        closeButton4.setBackground(new java.awt.Color(0, 0, 204));
        closeButton4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        closeButton4.setForeground(new java.awt.Color(255, 255, 255));
        closeButton4.setText("Consola");
        closeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ordenar por:");

        Nombre1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setText("Name");
        Nombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre1MouseClicked(evt);
            }
        });

        Horas1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas1.setForeground(new java.awt.Color(255, 255, 255));
        Horas1.setText("Hours");
        Horas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas1MouseClicked(evt);
            }
        });

        Consola1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola1.setForeground(new java.awt.Color(255, 255, 255));
        Consola1.setText("Console");
        Consola1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola1MouseClicked(evt);
            }
        });

        Rating1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating1.setForeground(new java.awt.Color(255, 255, 255));
        Rating1.setText("Rating");
        Rating1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating1MouseClicked(evt);
            }
        });

        Rating2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating2.setForeground(new java.awt.Color(255, 255, 255));
        Rating2.setText("Rating");
        Rating2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating2MouseClicked(evt);
            }
        });

        Consola2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola2.setForeground(new java.awt.Color(255, 255, 255));
        Consola2.setText("Console");
        Consola2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola2MouseClicked(evt);
            }
        });

        Horas2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas2.setForeground(new java.awt.Color(255, 255, 255));
        Horas2.setText("Hours");
        Horas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas2MouseClicked(evt);
            }
        });

        Nombre2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setText("Name");
        Nombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre2MouseClicked(evt);
            }
        });

        Rating3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating3.setForeground(new java.awt.Color(255, 255, 255));
        Rating3.setText("Rating");
        Rating3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating3MouseClicked(evt);
            }
        });

        Consola3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola3.setForeground(new java.awt.Color(255, 255, 255));
        Consola3.setText("Console");
        Consola3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola3MouseClicked(evt);
            }
        });

        Horas3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas3.setForeground(new java.awt.Color(255, 255, 255));
        Horas3.setText("Hours");
        Horas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas3MouseClicked(evt);
            }
        });

        Nombre3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        Nombre3.setText("Name");
        Nombre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre3MouseClicked(evt);
            }
        });

        Rating4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating4.setForeground(new java.awt.Color(255, 255, 255));
        Rating4.setText("Rating");
        Rating4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating4MouseClicked(evt);
            }
        });

        Consola4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola4.setForeground(new java.awt.Color(255, 255, 255));
        Consola4.setText("Console");
        Consola4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola4MouseClicked(evt);
            }
        });

        Horas4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas4.setForeground(new java.awt.Color(255, 255, 255));
        Horas4.setText("Hours");
        Horas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas4MouseClicked(evt);
            }
        });

        Nombre4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        Nombre4.setText("Name");
        Nombre4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre4MouseClicked(evt);
            }
        });

        Rating5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating5.setForeground(new java.awt.Color(255, 255, 255));
        Rating5.setText("Rating");
        Rating5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating5MouseClicked(evt);
            }
        });

        Consola5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola5.setForeground(new java.awt.Color(255, 255, 255));
        Consola5.setText("Console");
        Consola5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola5MouseClicked(evt);
            }
        });

        Horas5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas5.setForeground(new java.awt.Color(255, 255, 255));
        Horas5.setText("Hours");
        Horas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas5MouseClicked(evt);
            }
        });

        Nombre5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        Nombre5.setText("JNames");
        Nombre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre5MouseClicked(evt);
            }
        });

        Portada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portada1ActionPerformed(evt);
            }
        });

        Portada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portada2ActionPerformed(evt);
            }
        });

        Portada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portada3ActionPerformed(evt);
            }
        });

        Portada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portada4ActionPerformed(evt);
            }
        });

        Portada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Portada5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)
                        .addGap(421, 421, 421)
                        .addComponent(nextButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(closeButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Portada2)
                                            .addComponent(Portada3)
                                            .addComponent(Portada4)
                                            .addComponent(Portada5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre2)
                                                .addGap(18, 18, 18)
                                                .addComponent(Horas2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Consola2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Rating2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre3)
                                                .addGap(18, 18, 18)
                                                .addComponent(Horas3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Consola3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Rating3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre4)
                                                .addGap(18, 18, 18)
                                                .addComponent(Horas4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Consola4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Rating4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre5)
                                                .addGap(18, 18, 18)
                                                .addComponent(Horas5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Consola5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Rating5))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Portada1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nombre1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Horas1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Consola1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Rating1)))))
                        .addGap(0, 576, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton1)
                    .addComponent(closeButton2)
                    .addComponent(closeButton3)
                    .addComponent(closeButton4))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1)
                    .addComponent(Horas1)
                    .addComponent(Consola1)
                    .addComponent(Rating1)
                    .addComponent(Portada1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre2)
                    .addComponent(Horas2)
                    .addComponent(Consola2)
                    .addComponent(Rating2)
                    .addComponent(Portada2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre3)
                    .addComponent(Horas3)
                    .addComponent(Consola3)
                    .addComponent(Rating3)
                    .addComponent(Portada3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre4)
                    .addComponent(Horas4)
                    .addComponent(Consola4)
                    .addComponent(Rating4)
                    .addComponent(Portada4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre5)
                    .addComponent(Horas5)
                    .addComponent(Consola5)
                    .addComponent(Rating5)
                    .addComponent(Portada5))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(backButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (page == 1) {
            page = max;
        } else {
            page--;
        }
        updateText();
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (page == max) {
            page = 1;
        } else {
            page++;
        }
        System.out.println(page);
        updateText();
    }//GEN-LAST:event_nextButtonActionPerformed
    public void updateText() {
        ResultSet rs;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(DbURL, Username, password);
            Statement statement = connection.createStatement();
            rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + 0) + ", 1;");
            if (rs.next()) {
                

                String link = rs.getString(1);
                System.out.println(rs.getString(1));
                BufferedImage portada = null;
                try {
                    URL url = new URL(link);
                    portada = ImageIO.read(url);

                    //If successful, process the message
                } catch (IOException e) {
                    System.out.println("Unable to retrieve Image!!!");
                }
                Icon caratula1;
                float width = portada.getWidth();
                float height = portada.getHeight() * (100 / width);
                int high = Math.round(height);
                Image image = portada.getScaledInstance(100, high, Image.SCALE_DEFAULT);
                caratula1 = new ImageIcon(image);
                Portada1.setOpaque(false);
                Portada1.setContentAreaFilled(false);
                Portada1.setBorderPainted(false);
                Portada1.setIcon(caratula1);
                Consola1.setText(rs.getString(2));
                Horas1.setText("Horas: " + rs.getFloat(4));
                Rating1.setText("Rating: " + rs.getFloat(6));
                Nombre1.setText(rs.getString(7));
            } else {
                // no record found
            }
            connection.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        if (page * 5 + 1 < max) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(DbURL, Username, password);
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + 1) + ", 1;");
                if (rs.next()) {

                    String link = rs.getString(1);
                    BufferedImage portada = null;
                    try {
                        URL url = new URL(link);
                        portada = ImageIO.read(url);

                        //If successful, process the message
                    } catch (IOException e) {
                        System.out.println("Unable to retrieve Image!!!");
                    }
                    Icon caratula2;
                    float width = portada.getWidth();
                    float height = portada.getHeight() * (100 / width);
                    int high = Math.round(height);
                    Image image = portada.getScaledInstance(100, high, Image.SCALE_DEFAULT);
                    caratula2 = new ImageIcon(image);
                    Portada2.setOpaque(false);
                    Portada2.setContentAreaFilled(false);
                    Portada2.setBorderPainted(false);
                    Portada2.setIcon(caratula2);
                    Consola2.setText(rs.getString(2));
                    Horas2.setText("Horas: " + rs.getFloat(4));
                    Rating2.setText("Rating: " + rs.getFloat(6));
                    Nombre2.setText(rs.getString(7));
                } else {
                    // no record found
                }
                connection.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            Portada2.setOpaque(false);
            Portada2.setContentAreaFilled(false);
            Portada2.setBorderPainted(false);
            Portada2.setIcon(null);
            Consola2.setText("");
            Horas2.setText("");
            Rating2.setText("");
            Nombre2.setText("");
        }
        if (page * 5 + 2 < max) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(DbURL, Username, password);
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + 2) + ", 1;");
                if (rs.next()) {

                    String link = rs.getString(1);
                    BufferedImage portada = null;
                    try {
                        URL url = new URL(link);
                        portada = ImageIO.read(url);

                        //If successful, process the message
                    } catch (IOException e) {
                        System.out.println("Unable to retrieve Image!!!");
                    }
                    Icon caratula3;
                    float width = portada.getWidth();
                    float height = portada.getHeight() * (100 / width);
                    int high = Math.round(height);
                    Image image = portada.getScaledInstance(100, high, Image.SCALE_DEFAULT);
                    caratula3 = new ImageIcon(image);
                    Portada3.setOpaque(false);
                    Portada3.setContentAreaFilled(false);
                    Portada3.setBorderPainted(false);
                    Portada3.setIcon(caratula3);
                    Consola3.setText(rs.getString(2));
                    Horas3.setText("Horas: " + rs.getFloat(4));
                    Rating3.setText("Rating: " + rs.getFloat(6));
                    Nombre3.setText(rs.getString(7));
                } else {
                    // no record found
                }
                connection.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            Portada3.setOpaque(false);
            Portada3.setContentAreaFilled(false);
            Portada3.setBorderPainted(false);
            Portada3.setIcon(null);
            Consola3.setText("");
            Horas3.setText("");
            Rating3.setText("");
            Nombre3.setText("");
        }
        if (page * 5 + 3 < max) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(DbURL, Username, password);
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + 3) + ", 1;");
                if (rs.next()) {

                    String link = rs.getString(1);
                    BufferedImage portada = null;
                    try {
                        URL url = new URL(link);
                        portada = ImageIO.read(url);

                        //If successful, process the message
                    } catch (IOException e) {
                        System.out.println("Unable to retrieve Image!!!");
                    }
                    Icon caratula4;
                    float width = portada.getWidth();
                    float height = portada.getHeight() * (100 / width);
                    int high = Math.round(height);
                    Image image = portada.getScaledInstance(100, high, Image.SCALE_DEFAULT);
                    caratula4 = new ImageIcon(image);
                    Portada4.setOpaque(false);
                    Portada4.setContentAreaFilled(false);
                    Portada4.setBorderPainted(false);
                    Portada4.setIcon(caratula4);
                    Consola4.setText(rs.getString(2));
                    Horas4.setText("Horas:" + rs.getFloat(4));
                    Rating4.setText("Rating " + rs.getFloat(6));
                    Nombre4.setText(rs.getString(7));
                } else {
                    // no record found
                }
                connection.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            Portada4.setOpaque(false);
            Portada4.setContentAreaFilled(false);
            Portada4.setBorderPainted(false);
            Portada4.setIcon(null);
            Consola4.setText("");
            Horas4.setText("");
            Rating4.setText("");
            Nombre4.setText("");
        }
        if (page * 5 + 4 < max) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(DbURL, Username, password);
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + 4) + ", 1;");
                if (rs.next()) {

                    String link = rs.getString(1);
                    BufferedImage portada = null;
                    try {
                        URL url = new URL(link);
                        portada = ImageIO.read(url);

                        //If successful, process the message
                    } catch (IOException e) {
                        System.out.println("Unable to retrieve Image!!!");
                    }
                    Icon caratula5;
                    float width = portada.getWidth();
                    float height = portada.getHeight() * (100 / width);
                    int high = Math.round(height);
                    Image image = portada.getScaledInstance(100, high, Image.SCALE_DEFAULT);
                    caratula5 = new ImageIcon(image);
                    Portada5.setOpaque(false);
                    Portada5.setContentAreaFilled(false);
                    Portada5.setBorderPainted(false);
                    Portada5.setIcon(caratula5);
                    Consola5.setText(rs.getString(2));
                    Horas5.setText("Horas: " + rs.getFloat(4));
                    Rating5.setText("Rating: " + rs.getFloat(6));
                    Nombre5.setText(rs.getString(7));
                } else {
                    // no record found
                }
                connection.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            Portada5.setIcon(null);
            Portada5.setOpaque(false);
            Portada5.setContentAreaFilled(false);
            Portada5.setBorderPainted(false);
            Consola5.setText("");
            Horas5.setText("");
            Rating5.setText("");
            Nombre5.setText("");
        }

    }
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
        selector a = new selector();
        a.setVisible(true);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton1ActionPerformed
        order = "order by rating";
        page = 0;
        updateText();
    }//GEN-LAST:event_closeButton1ActionPerformed

    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        order = "order by hours";
        page = 0;
        updateText();
    }//GEN-LAST:event_closeButton2ActionPerformed

    private void closeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton3ActionPerformed
        order = "order by name";
        page = 0;
        updateText();
    }//GEN-LAST:event_closeButton3ActionPerformed

    private void closeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton4ActionPerformed
        order = "order by platform";
        page = 0;
        updateText();
    }//GEN-LAST:event_closeButton4ActionPerformed

    private void Nombre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre1MouseClicked

    }//GEN-LAST:event_Nombre1MouseClicked

    private void Horas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas1MouseClicked

    }//GEN-LAST:event_Horas1MouseClicked

    private void Consola1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola1MouseClicked
    }//GEN-LAST:event_Consola1MouseClicked

    private void Rating1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating1MouseClicked
    }//GEN-LAST:event_Rating1MouseClicked

    private void Nombre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre2MouseClicked

    private void Horas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Horas2MouseClicked

    private void Consola2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Consola2MouseClicked

    private void Rating2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Rating2MouseClicked

    private void Nombre3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre3MouseClicked
    }//GEN-LAST:event_Nombre3MouseClicked

    private void Horas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas3MouseClicked
    }//GEN-LAST:event_Horas3MouseClicked

    private void Consola3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola3MouseClicked
    }//GEN-LAST:event_Consola3MouseClicked

    private void Rating3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating3MouseClicked
    }//GEN-LAST:event_Rating3MouseClicked

    private void Nombre4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre4MouseClicked
    }//GEN-LAST:event_Nombre4MouseClicked

    private void Horas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas4MouseClicked
    }//GEN-LAST:event_Horas4MouseClicked

    private void Consola4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola4MouseClicked
    }//GEN-LAST:event_Consola4MouseClicked

    private void Rating4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating4MouseClicked
    }//GEN-LAST:event_Rating4MouseClicked

    private void Nombre5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre5MouseClicked
    }//GEN-LAST:event_Nombre5MouseClicked

    private void Horas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas5MouseClicked
    }//GEN-LAST:event_Horas5MouseClicked

    private void Consola5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola5MouseClicked
    }//GEN-LAST:event_Consola5MouseClicked

    private void Rating5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating5MouseClicked
    }//GEN-LAST:event_Rating5MouseClicked

    private void Portada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portada1ActionPerformed
        System.out.println("Boton pulsado");
        open(1);    }//GEN-LAST:event_Portada1ActionPerformed

    private void Portada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portada2ActionPerformed
        open(2);        // TODO add your handling code here:
    }//GEN-LAST:event_Portada2ActionPerformed

    private void Portada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portada4ActionPerformed
        open(4);        // TODO add your handling code here:
    }//GEN-LAST:event_Portada4ActionPerformed

    private void Portada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portada5ActionPerformed
        open(5);   // TODO add your handling code here:
    }//GEN-LAST:event_Portada5ActionPerformed

    private void Portada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Portada3ActionPerformed
        open(3);        // TODO add your handling code here:
    }//GEN-LAST:event_Portada3ActionPerformed
    public void open(int i) {
        ResultSet rs;
        Icon caratula = null;
        String Consola = "";
        String description = "";
        Float Horas = 0.0f;
        Float Percent = 0.0f;
        Float Rating = 0.0f;
        String Nombre = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(DbURL, Username, password);
            Statement statement = connection.createStatement();

            rs = statement.executeQuery("Select * from your_games_records " + order + " limit " + ((page - 1) * 5 + i - 1) + ", 1;");

            if (rs.next()) {
                String link = rs.getString(1);
                BufferedImage portada = null;
                try {
                    URL url = new URL(link);
                    portada = ImageIO.read(url);
                } catch (IOException e) {
                    System.out.println("Unable to retrieve Image!!!");
                }
                float width = portada.getWidth();
                float height = portada.getHeight() * (500 / width);
                int high=(int)height;
                Image image = portada.getScaledInstance(500, high, Image.SCALE_DEFAULT);
                caratula = new ImageIcon(image);
                Consola = rs.getString(2);
                description = rs.getString(3);
                Horas = rs.getFloat(4);
                Percent = rs.getFloat(5);
                Rating = rs.getFloat(6);
                Nombre = rs.getString(7);
View_Entry v = new View_Entry(caratula, Consola, description, Horas, Percent, Rating, Nombre);
            v.setVisible(true);
            } else {
                System.out.println("error");
            }
            connection.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Entries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Entries();
            }
        });
    }

    public static void error1() {
        JOptionPane.showMessageDialog(null, "ERROR \n Debe introducir alguna entrada antes de poder entrar aquí.");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Consola1;
    private javax.swing.JLabel Consola2;
    private javax.swing.JLabel Consola3;
    private javax.swing.JLabel Consola4;
    private javax.swing.JLabel Consola5;
    private javax.swing.JLabel Horas1;
    private javax.swing.JLabel Horas2;
    private javax.swing.JLabel Horas3;
    private javax.swing.JLabel Horas4;
    private javax.swing.JLabel Horas5;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JLabel Nombre5;
    private javax.swing.JButton Portada1;
    private javax.swing.JButton Portada2;
    private javax.swing.JButton Portada3;
    private javax.swing.JButton Portada4;
    private javax.swing.JButton Portada5;
    private javax.swing.JLabel Rating1;
    private javax.swing.JLabel Rating2;
    private javax.swing.JLabel Rating3;
    private javax.swing.JLabel Rating4;
    private javax.swing.JLabel Rating5;
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton closeButton3;
    private javax.swing.JButton closeButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
