
import java.awt.image.BufferedImage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Marc
 */
import javax.swing.*;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import java.sql.*;

public class View_Entry extends javax.swing.JFrame {

    
    /**
     * Creates new form View_Entries
     */
    public Icon caratula;
    public String platform;
    public String description;
    public float hours;
    public float percent;
    public float rating;
    public String name;

    public View_Entry(Icon c, String plat, String d, float h, float p, float r, String n) {
        this.caratula=c;
        this.platform=plat;
        this.description=d;
        this.hours=h;
        this.percent=p;
        this.rating=r;
        this.name=n;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Portada1 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Horas1 = new javax.swing.JLabel();
        Consola1 = new javax.swing.JLabel();
        Rating1 = new javax.swing.JLabel();
        Rating2 = new javax.swing.JLabel();
        Rating3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(109, 8, 214));

        Portada1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Portada1.setForeground(new java.awt.Color(255, 255, 255));
        Portada1.setIcon(caratula);
        Portada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Portada1MouseClicked(evt);
            }
        });

        Nombre1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setText(name);
        Nombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre1MouseClicked(evt);
            }
        });

        Horas1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Horas1.setForeground(new java.awt.Color(255, 255, 255));
        Horas1.setText(platform);
        Horas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horas1MouseClicked(evt);
            }
        });

        Consola1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Consola1.setForeground(new java.awt.Color(255, 255, 255));
        Consola1.setText(description);
        Consola1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Consola1MouseClicked(evt);
            }
        });

        Rating1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating1.setForeground(new java.awt.Color(255, 255, 255));
        Rating1.setText(Float.toString(percent));
        Rating1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating1MouseClicked(evt);
            }
        });

        Rating2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating2.setForeground(new java.awt.Color(255, 255, 255));
        Rating2.setText(Float.toString(hours));
        Rating2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating2MouseClicked(evt);
            }
        });

        Rating3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Rating3.setForeground(new java.awt.Color(255, 255, 255));
        Rating3.setText(Float.toString(rating));
        Rating3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rating3MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rating3)
                            .addComponent(Rating2)
                            .addComponent(Rating1)
                            .addComponent(Consola1)
                            .addComponent(Nombre1)
                            .addComponent(Portada1)
                            .addComponent(Horas1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton1)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Portada1)
                .addGap(47, 47, 47)
                .addComponent(Nombre1)
                .addGap(18, 18, 18)
                .addComponent(Horas1)
                .addGap(18, 18, 18)
                .addComponent(Consola1)
                .addGap(18, 18, 18)
                .addComponent(Rating2)
                .addGap(18, 18, 18)
                .addComponent(Rating1)
                .addGap(18, 18, 18)
                .addComponent(Rating3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rating1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating1MouseClicked
    }//GEN-LAST:event_Rating1MouseClicked
    private void Consola1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Consola1MouseClicked
    }//GEN-LAST:event_Consola1MouseClicked
    private void Horas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horas1MouseClicked
    }//GEN-LAST:event_Horas1MouseClicked
    private void Nombre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre1MouseClicked
    }//GEN-LAST:event_Nombre1MouseClicked
    private void Portada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Portada1MouseClicked
    }//GEN-LAST:event_Portada1MouseClicked
    private void Rating2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating2MouseClicked
    }//GEN-LAST:event_Rating2MouseClicked
    private void Rating3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rating3MouseClicked
    }//GEN-LAST:event_Rating3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Consola1;
    private javax.swing.JLabel Horas1;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Portada1;
    private javax.swing.JLabel Rating1;
    private javax.swing.JLabel Rating2;
    private javax.swing.JLabel Rating3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
